//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskOrganizer.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Manager { get; set; }
        public string Address { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    }
}
