//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskOrganizer.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DeptId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string ManagerName { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_on { get; set; }
    }
}
