//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskOrganizer.database
{
    using System;
    
    public partial class sp_GetFilteredData_Result1
    {
        public int TaskId { get; set; }
        public string Assignee { get; set; }
        public string TaskName { get; set; }
        public string Stage { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool Status { get; set; }
    }
}
