//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskOrganizer.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int TaskId { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
