//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskOrganizer.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
        public int TaskId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TaskName { get; set; }
        public string Assignee { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> TaskCreationDate { get; set; }
        public bool Status { get; set; }
        public string Stage { get; set; }
        public int Priority { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    }
}
